### Token Create
POST http://202.70.136.24:3020/api/login
Content-Type: application/json

{
    "userName": "kotakelektronik@gmail.com",
    "password": "p5fuNGds"
}

### Display all rumah sakit resource
GET http://localhost:3020/api/rumahsakit?nama=si
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImtvZGVfcnMiOm51bGwsImlhdCI6MTY3NDE5NzQ4NiwiZXhwIjoxNjc0MTk4MDg2fQ.M7K5Z0N6aMR0RBELFRj2o3tkqmsQGtOMquMOAl7z9ss

### Display the specific rumah sakit resource
GET http://localhost:3020/api/rumahsakit/1108017
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImN1bWFkd2lwQGdtYWlsLmNvbSIsImlhdCI6MTYzNzI4ODkyMywiZXhwIjoxNjM3Mjg5NTIzfQ.iB_rfRHDek5LFH9O1IjlQyie23KeS4TZ0TAWRCt48P0

### Display all hospital resource
GET http://202.70.136.24:3020/api/hospital
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImtvZGVfcnMiOm51bGwsImlhdCI6MTY3NDE5ODAyMCwiZXhwIjoxNjc0MTk4NjIwfQ.aQIckhB1U7TQEWyla3ble0H0GvosutRh2CPo-Y1iMGU

### Display Pelayanan
GET http://127.0.0.1:3020/api/pelayanan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImtvZGVfcnMiOm51bGwsImlhdCI6MTY3MjI5NDc1MSwiZXhwIjoxNjcyMjk1MzUxfQ.yu7_GYjzFyYLvOvdRGNuREEe15wqM3lu4lJlIEadEf8