### Token Create
POST http://localhost:3020/api/login
Content-Type: application/json

{
    "userName": "kotakelektronik@gmail.com",
    "password": "p5fuNGds"
}

### Laporan Covid
POST http://202.70.136.24:3020/api/laporancovid19versi3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJrb3Rha2VsZWt0cm9uaWtAZ21haWwuY29tIiwia29kZV9ycyI6Ijk5OTk5OTkiLCJpYXQiOjE2ODQ3Mzg2NzcsImV4cCI6MTY4NDczOTI3N30.dWqfDAjqbpAbdpQ8gPBe9ATHBv2Yyr60gcWF3uNjX3o
Content-Type: application/json

{
    "kewarganegaraanId": "ID",
    "nik": "7106090901570051",
    "noPassport": null,
    "asalPasienId": "0",
    "noRM": "00709990",
    "namaLengkapPasien": "Pasien Testing Bridging",
    "namaInisialPasien": "PTB'",
    "tanggalLahir": "1958-01-09",
    "email": "-",
    "noTelp": "081350099886",
    "jenisKelaminId": "L",
    "domisiliKecamatanId": "717109",
    "domisiliKabKotaId": "7171",
    "domisiliProvinsiId": "71",
    "pekerjaanId": "1",
    "tanggalMasuk": "2019-12-03",
    "jenisPasienId": "3",
    "varianCovidId": "1",
    "statusPasienId": "1",
    "statusCoInsidenId": "0",
    "statusRawatId": "29",
    "alatOksigenId": null,
    "penyintasId": "0",
    "tanggalOnsetGejala": "2022-02-09",
    "kelompokGejalaId": "1",
    "gejala": {
        "demamId": "0",
        "batukId": "0",
        "pilekId": "0",
        "sakitTenggorokanId": "0",
        "sesakNapasId": "0",
        "lemasId": "0",
        "nyeriOtotId": "0",
        "mualMuntahId": "0",
        "diareId": "0",
        "anosmiaId": "0",
        "napasCepatId": "0",
        "frekNapas30KaliPerMenitId": "0",
        "distresPernapasanBeratId": "0",
        "lainnyaId": "0"
    }
}

### Display all rumah sakit resource
GET http://localhost:3020/api/rumahsakit?provinsiId=31&kabKotaId=3173
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImtvZGVfcnMiOm51bGwsImlhdCI6MTY5MDk1Njg5MCwiZXhwIjoxNjkwOTU3NDkwfQ.jlh4iRCaL6zEVVKXPeGtpneW76TFL_ZT5xaI9I5XOXw

### Display the specific rumah sakit resource
GET http://localhost:3020/api/rumahsakit/1108017
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImN1bWFkd2lwQGdtYWlsLmNvbSIsImlhdCI6MTYzNzI4ODkyMywiZXhwIjoxNjM3Mjg5NTIzfQ.iB_rfRHDek5LFH9O1IjlQyie23KeS4TZ0TAWRCt48P0

### Display all hospital resource
GET http://202.70.136.24:3020/api/hospital
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImtvZGVfcnMiOm51bGwsImlhdCI6MTY3NDE5ODAyMCwiZXhwIjoxNjc0MTk4NjIwfQ.aQIckhB1U7TQEWyla3ble0H0GvosutRh2CPo-Y1iMGU

### Display Pelayanan
GET http://127.0.0.1:3020/api/pelayanan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcl9uYW1lIjoia290YWtlbGVrdHJvbmlrQGdtYWlsLmNvbSIsImtvZGVfcnMiOm51bGwsImlhdCI6MTY3MjI5NDc1MSwiZXhwIjoxNjcyMjk1MzUxfQ.yu7_GYjzFyYLvOvdRGNuREEe15wqM3lu4lJlIEadEf8

### User Insert
POST http://127.0.0.1:3020/api/tasjil
Content-Type: application/json

{
    "userName": "ujicoba@gmail.com",
    "fullName": "ujicoba",
    "appName": "ujicoba",
    "stakeHolderName": "ujicoba",
    "ipAddress": "1",
    "activatedDate": "2023-01-01 00:00:00",
    "expiredDate": "2023-01-31 00:00:00",
    "isActive": "1",
    "faskesId": null
}
